### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by zabihshaik** [whitphx/streamlit-stt-app#144]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://whitphx-streamlit-stt-app-app-deepspeech-m6tt1k.streamlit.app/whitphx/streamlit-stt-app/main/app_deepspeech.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

Screenshot below:

![Webrtc error](https://github.com/whitphx/streamlit-stt-app/assets/91183455/7810e005-f265-4c10-ab41-c729ab050656)

**Comment by whitphx** [comment]
Thanks! Looks like it's been fixed with an auto reboot.

**Comment by zabihshaik** [comment]
Thanks for the response @whitphx 👍
