### ISSUE TITLE
how to change webrtc from udp to tcp to avoid missing data?

### ISSUE THREAD

**Issue by Jackiexiao** [whitphx/streamlit-stt-app#27]
in stt / recording audio scenario , maybe reliability is more important, is it possible to choose ICE tcp candidates in webrtc-streamlit?

**Comment by whitphx** [comment]
It's not supported, and as written in [this StackOverflow topic](https://stackoverflow.com/questions/18897917/does-webrtc-use-tcp-or-udp), it's not recommended.

Even if UDP's unreliability is a problem, UDP is a good choice for real-time purpose and there is a necessary tradeoff between speed and quality.

FYI, some production-level conference systems like Zoom have finer audio quality control, however, such software has its own audio transmitting implementation on WebRTC DataChannel (which natively supports TCP-only mode, BTW) and it's beyond streamlit-webrtc's scope.

**Comment by Jackiexiao** [comment]
get it, thx very much for your reply!
